Add template disks
oVirt/ovirt-ansible-image-template pull request #50
Opened 2019-09-25 11:16 UTC by mnecas

Fixes #32 
Added variable template_disks. Its for adding multiple disks to template.
@machacekondra @mwperina

2019-10-08 14:15 UTC, mnecas commented on README.md
> +| name               | UNDEF          | The name of the additional disk.  |
add required

2019-10-08 14:16 UTC, mnecas commented on tasks/qcow2_image.yml
> +          size: "{{ item.size | default(omit) }}"
item.size | mandatory

2019-10-08 14:16 UTC, mnecas commented on tasks/qcow2_image.yml
> +          vm_name: "{{ vm_name }}"
item.size | mandatory

2019-10-08 14:17 UTC, mnecas commented on tasks/qcow2_image.yml
> +          name: "{{ item.name }}"
item.name | madatory

2020-03-20 11:25 UTC, mwperina requested changes
Looks good, just small rephrase in documentation

2020-03-20 11:25 UTC, mwperina commented on README.md
> +the disk will be looked up by id and will update name of the disk if it differs from the name passed in name parameter. |
`The disk will be looked up by id and its name will be updated if it differs from the name passed in name parameter`

2020-03-20 11:57 UTC, mwperina approved these changes
+1

2020-03-20 11:58 UTC, merged